config:
  storehub:platformDomain: storehub.local
  storehub:apiImage: ghcr.io/barreramelchorf/storehub-api:latest
  storehub:webImage: ghcr.io/barreramelchorf/storehub-web:latest
  storehub:migrateImage: ghcr.io/barreramelchorf/storehub-migrate:latest
  storehub:apiReplicas: "1"
  storehub:webReplicas: "1"
  storehub:postgresPassword:
    secure: AAABAAM8i50i1R59mcA++XdaSY/zArn5luExfJgMks9IM+sjLwnxMP1fL2q4ZA==
  storehub:redisPassword:
    secure: AAABANImOdf8428ZDdFDJnjRLeFQs7KtoTCpAN0wZDARg2SJSNP4eKEQRg==
  storehub:jwtSecret:
    secure: AAABAONayzEybZtc2fE1IIytcf2UIkBYY7SbU7Z60UP4piZ98XyeDiI9pqqiYrA=
  storehub:minioRootPassword:
    secure: AAABADI6EDYMgS7L0iImyuH2rZucCqWqZ2gAoHvDlGOWXn/gWsD421Xsqg==
  storehub:ghcrToken:
    secure: AAABAF4yPkD/EHxs69DciWDrG1UrU1AIF71/WuaDuYmLjHRwOnns2OpvGQeu+nqOALanXO56Z3G/kpymKvpHsupEKUcbHVsm
