config:
  storehub:platformDomain: storehub.local
  storehub:version: "v0.1.0"
  storehub:migrationsVersion: "v0.1.2"
  storehub:apiReplicas: "1"
  storehub:webReplicas: "1"
  storehub:postgresPassword:
    secure: AAABALNET/XBMFbbRehOl0Ph0ALVoSgcPPqcyFLfCZYnwQog4duVDHCn+35N1Q==
  storehub:redisPassword:
    secure: AAABANE8mYtfbUIdV/zZWVzPrNaDJiMicUyuypL3khwlBVwoeF/MATW7ZA==
  storehub:jwtSecret:
    secure: AAABAGpaJZEAhGIBUzlW02ytLX4tnNiMZvw6ubzUlV5xYYBBSKk324AnXDr44zg=
  storehub:minioRootPassword:
    secure: AAABAKexI0mf89QC7E+P7dAHrHcjbkt8fu3IGRCBk18jYwOCK0Co0ZE4vQ==
  storehub:ghcrToken:
    secure: AAABAKeVLoopQgBsgJr3L3Zwb6lKpaODL5UKZcFIF4Vfp8cee1KtuWv90ANdwXKcaiWhBpOVBS5MPfzofRbIMWysJPNaeYdB
