config:
  storehub-infra:platformDomain: storehub.local
  storehub-infra:acmeEmail: barreramelchorf@gmail.com
  storehub-infra:apiImage: ghcr.io/barreramelchorf/storehub-api:latest
  storehub-infra:webImage: ghcr.io/barreramelchorf/storehub-web:latest
  storehub-infra:migrateImage: ghcr.io/barreramelchorf/storehub-migrate:latest
  storehub-infra:apiReplicas: "1"
  storehub-infra:webReplicas: "1"
  storehub-infra:postgresPassword:
    secure: AAABAFakeEncryptedValueForDev==
  storehub-infra:redisPassword:
    secure: AAABAFakeEncryptedValueForDev==
  storehub-infra:jwtSecret:
    secure: AAABAFakeEncryptedValueForDev==
  storehub-infra:minioRootPassword:
    secure: AAABAFakeEncryptedValueForDev==
